### ISSUE TITLE
Update to iced 0.13 planned?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [Joylei/plotters-iced#38]
We are working on updating our (that uses plotters-iced) to the 0.13 version of iced, that brings quite some change.

I wanted to check if you planned to do the same. 

We're having some issues, and it might be impossible unless plotters-iced also updates.

So, before taking any drastic decisions, or investing too much time in a dead-end, U thought I'd ask here.

Thanks for any help!

**Comment by GyulyVGC** [comment]
I'm not the official maintainer, but a contributor here.
Usually this library is updated after a new version of iced is released, and I think it doesn't make much sense to keep the pace with iced's master branch since things there are typically unstable and could change.
But for a more complete response, let's see what Joylei thinks about this.

**Comment by Joylei** [comment]
I'd like to update the library once a new version of iced is released.

You can clone the lib and try to update  the new version of iced.

Let me know if you need helps.
